version: '3'

services:
  he853api:
    build: he853api
    container_name: he853api
    privileged: true
    volumes:
      - /dev:/dev
    environment:
      - TIMEZONE=Europe/Amsterdam
      - HE853_API_KEY=""    # For development no API key.
    restart: always
    ports:
      - 8000:8000
    
